### ISSUE TITLE
After editing and saving, another tab gets closed

### ISSUE THREAD

**Issue by VitGottwald** [eclipse-che4z/che-che4z-explorer-for-endevor#221]
When I edit an element and choose to close its tab, then select save, it is saved. But right after that another tab is closed.

**Comment by nickImbirev** [comment]
Hey @VitGottwald!

I'm so sorry for this, I understand the issue, regretfully, it comes with some VSCode API restrictions, which we did not consider before hand.

This behaviour should be updated now (since v1.0.0), the E4E should close the edit session immediately after the save button is clicked. I think, this might be a temporarily resolution... Can I ask you to take a look?

Also, we have another issue to rethink the edit/upload feature UX in here: #189 in general, I can propose to continue the discussion there. What do you think?

Hope that helps

Nikolai

**Comment by roman-kupriyanov** [comment]
Should be fixed in 1.7.2.
