### ISSUE TITLE
Update Option 

### ISSUE THREAD

**Issue by Morridt** [eclipse-che4z/che-che4z-explorer-for-endevor#347]
**Is your feature request related to a problem? Please describe.**
Wondering why there is no update feature. I've searched through all the issues to see if this has been raised previously, and tried to determine if I have missed something.

I'm generating with copyback, source from up the map to my entry environment.  When editing in this environment I'm not seeing syntax errors or copybook resolutions. 
So I retrieved with dependencies and edited locally.  The only way I can see to UPDATE the source in the entry environment is by issuing a zowe cli UPDATE command (we have not tried sync at this point).

**Describe the solution you'd like**
Adding an option to the right click menu of an element to do an update from local. It should know it exists based on standard folder structure created during retrieve, so can default the source and destination. Or it could ask for a file similar to ADD. If I have it signed out I can't see any issues.

**Describe alternatives you've considered**
At some point we'll look at workspace sync to determine if it can be used (we are early days of adoption), but still think an update option would be good.

**Additional context**

**Comment by zdmullen** [comment]
Hi @Morridt -- thanks for sharing the idea. Several things:
- When the retrieve with dependencies was added, the return sync to Endevor was indeed expected to be via Zowe CLI. We are actually looking to deprecate the functionality in favor of a different editing experience altogether and because of the next point
- With respect to copybook resolution, we are working on an integration with the COBOL LSP extension (in Code4z) to properly retrieve copybooks. I can share more about this in an email
- We are working on splitting the edit and upload behavior in the extension (i.e. select an element to edit, work on it, save it, and then decide to upload to Endevor (so that especially users with autosave don't inadvertently create so many change levels))
Feel free to email me at zachariah.mullen@broadcom.com for more information about the above plans and to let me know if you would like to jump on a call to discuss your desired workflows. Thanks!

**Comment by Morridt** [comment]
Thanks @zdmullen 
We've actually created a VSCode task to help with UPDATE with input from extension **Command Variable** to select a local file (under the Endevor\env\sys\subsus\ folders), then feeding that through a script to run the zowe update command.
I'll send you an email.

**Comment by roman-kupriyanov** [comment]
Since VSCode task is there to help, I proceed with closing this issue.
